version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: "database"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
  web:
    # build: .
    image: alisalim17/nextsyncapi:latest
    container_name: "api"
    env_file:
      - .env.prod
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - fullstack
    volumes:
      - .:/usr/src/app
    command: 
      - /bin/sh
      - -c
      - |
        make migrate_db 
        make dev

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge